### ISSUE TITLE
Reading new ldb files

### ISSUE THREAD

**Issue by Elec0** [JotaroSan/N5E-Conversion#2]
I'm currently using your `jutsus.db` (thanks for doing all that work!)
With the new update to move to LevelDB, the data obviously isn't stored in raw json anymore, so I'm trying to figure out how to read it.

I've tried using the FoundryVTT-cli, but none of the `fvtt package [...]` commands seemingly output anything.

Do you have some source of truth file for the jutsus I can pull from, or do you know how to read the new files programmatically?

**Comment by JotaroSan** [comment]
Hey Aaron,
Sorry to hear about this, but I believe I may have a solution nearly ready
for you lol. I'm currently working on a release to go out today/tomorrow
that will upgrade the compendiums to the new version being used in Foundry
V 11 :D. I've got a few minor issues to resolve then I'll be releasing that
to the public. Stay tuned on my github or the Discord for updates :D

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Elec0** [comment]
Awesome, that's great to hear. I'll keep an eye out for that, then!
